// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used by prisma generate/migrate. For Vercel build, generate only needs a placeholder (no DB connection).
    url: process.env["DATABASE_URL"] ?? "file:./prisma/dev.db",
  },
});
